# Generated by Django 4.2.7 on 2023-12-12 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'managed': False},
        ),
    ]
